### PR TITLE
Add planning and retrospective notes

### PR DESCRIPTION
**Pull request by dcwalk**
Figured we should add the notes into the repo too just to have everything in one place as opposed to strewn across services

### CODE REVIEW

**Comment by benhylau** [comment]
@garrying I think you can add it

**Comment by dcwalk** [comment]
please do @garrying!

**Comment by dcwalk** [comment]
I added! Just re-downloaded the markdown. Thanks for those additional thoughts 😊

**Comment by benhylau** [comment]
lgtm

**Comment by dcwalk** [comment]
MERGE IT IN!!!

**Pull request merged**
